
/*
	Estados del reducer
*/
export const VER_ACTIVIDAD = 'VER_ACTIVIDAD';
export const INSERTAR_ACTIVIDAD = 'INSERTAR_ACTIVIDAD';
export const ELIMINAR_ACTIVIDAD = 'ELIMINAR_ACTIVIDAD';
export const LISTAR_ACTIVIDADES = 'LISTAR_ACTIVIDADES';



/*
	Estados de API
*/
export const ERROR_INSERTAR_ACTIVIDAD = 'ERROR_INSERTAR_ACTIVIDAD';
export const ERROR_ACTUALIZAR_ACTIVIDAD = 'ERROR_ACTUALIZAR_ACTIVIDAD';
export const ERROR_ELIMINAR_ACTIVIDAD = 'ERROR_ELIMINAR_ACTIVIDAD';
export const ERROR_LISTAR_ACTIVIDAD = 'ERROR_LISTAR_ACTIVIDAD';
export const ERROR_ACTIVIDAD = 'ERROR_ACTIVIDAD';

export const SUCCESSFULL_INSERT_ACTIVIDAD = 'SUCCESSFULL_INSERT_ACTIVIDAD';
export const SUCCESSFULL_UPDATE_ACTIVIDAD = 'SUCCESSFULL_UPDATE_ACTIVIDAD';
export const SUCCESSFULL_DELETE_ACTIVIDAD = 'SUCCESSFULL_DELETE_ACTIVIDAD';