
/*
	Estados del reducer
*/
export const VER_ADJUNTO_TAREAS = 'VER_ADJUNTO_TAREAS';
export const INSERTAR_ADJUNTO_TAREAS = 'INSERTAR_ADJUNTO_TAREAS';
export const ELIMINAR_ADJUNTO_TAREAS = 'ELIMINAR_ADJUNTO_TAREAS';
export const LISTAR_ADJUNTO_TAREAS = 'LISTAR_ADJUNTO_TAREAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_ADJUNTO_TAREAS = 'ERROR_INSERTAR_ADJUNTO_TAREAS';
export const ERROR_ACTUALIZAR_ADJUNTO_TAREAS = 'ERROR_ACTUALIZAR_ADJUNTO_TAREAS';
export const ERROR_ELIMINAR_ADJUNTO_TAREAS = 'ERROR_ELIMINAR_ADJUNTO_TAREAS';
export const ERROR_LISTAR_ADJUNTO_TAREAS = 'ERROR_LISTAR_ADJUNTO_TAREAS';
export const ERROR_ADJUNTO_TAREAS = 'ERROR_ADJUNTO_TAREAS';

export const SUCCESSFULL_INSERT_ADJUNTO_TAREAS = 'SUCCESSFULL_INSERT_ADJUNTO_TAREAS';
export const SUCCESSFULL_UPDATE_ADJUNTO_TAREAS = 'SUCCESSFULL_UPDATE_ADJUNTO_TAREAS';
export const SUCCESSFULL_DELETE_ADJUNTO_TAREAS = 'SUCCESSFULL_DELETE_ADJUNTO_TAREAS';