
/*
	Estados del reducer
*/
export const VER_ASIGNACION_TAREA = 'VER_ASIGNACION_TAREA';
export const INSERTAR_ASIGNACION_TAREA = 'INSERTAR_ASIGNACION_TAREA';
export const ELIMINAR_ASIGNACION_TAREA = 'ELIMINAR_ASIGNACION_TAREA';
export const LISTAR_ASIGNACION_TAREAS = 'LISTAR_ASIGNACION_TAREAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_ASIGNACION_TAREA = 'ERROR_INSERTAR_ASIGNACION_TAREA';
export const ERROR_ACTUALIZAR_ASIGNACION_TAREA = 'ERROR_ACTUALIZAR_ASIGNACION_TAREA';
export const ERROR_ELIMINAR_ASIGNACION_TAREA = 'ERROR_ELIMINAR_ASIGNACION_TAREA';
export const ERROR_LISTAR_ASIGNACION_TAREAS = 'ERROR_LISTAR_ASIGNACION_TAREAS';
export const ERROR_ASIGNACION_TAREA = 'ERROR_ASIGNACION_TAREA';

export const SUCCESSFULL_INSERT_ASIGNACION_TAREA = 'SUCCESSFULL_INSERT_ASIGNACION_TAREA';
export const SUCCESSFULL_UPDATE_ASIGNACION_TAREA = 'SUCCESSFULL_UPDATE_ASIGNACION_TAREA';
export const SUCCESSFULL_DELETE_ASIGNACION_TAREA = 'SUCCESSFULL_DELETE_ASIGNACION_TAREA';