/*
	Estados del reducer
*/
export const VER_COMPETENCIA = 'VER_COMPETENCIA';
export const INSERTAR_COMPETENCIA = 'INSERTAR_COMPETENCIA';
export const ELIMINAR_COMPETENCIA = 'ELIMINAR_COMPETENCIA';
export const LISTAR_COMPETENCIAS = 'LISTAR_COMPETENCIA';


/*
	Estados de API
*/
export const ERROR_INSERTAR_COMPETENCIA = 'ERROR_INSERTAR_COMPETENCIA';
export const ERROR_ACTUALIZAR_COMPETENCIA = 'ERROR_ACTUALIZAR_COMPETENCIA';
export const ERROR_ELIMINAR_COMPETENCIA = 'ERROR_ELIMINAR_COMPETENCIA';
export const ERROR_LISTAR_COMPETENCIA = 'ERROR_LISTAR_COMPETENCIA';
export const ERROR_COMPETENCIA = 'ERROR_COMPETENCIA';

export const SUCCESSFULL_INSERT_COMPETENCIA = 'SUCCESSFULL_INSERT_COMPETENCIA';
export const SUCCESSFULL_UPDATE_COMPETENCIA = 'SUCCESSFULL_UPDATE_COMPETENCIA';
export const SUCCESSFULL_DELETE_COMPETENCIA = 'SUCCESSFULL_DELETE_COMPETENCIA';