/*
	Estados del reducer
*/
export const VER_CORREOS_ENVIADOS = 'VER_CORREOS_ENVIADOS';
export const INSERTAR_CORREO_ENVIADO = 'INSERTAR_CORREOS_ENVIADOS';
export const ELIMINAR_CORREO_ENVIADO = 'ELIMINAR_CORREOS_ENVIADOS';
export const LISTAR_CORREOS_ENVIADOS = 'LISTAR_CORREOS_ENVIADOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_CORREO_ENVIADO = 'ERROR_INSERTAR_CORREOS_ENVIADO';
export const ERROR_ACTUALIZAR_CORREO_ENVIADO = 'ERROR_ACTUALIZAR_CORREOS_ENVIADO';
export const ERROR_ELIMINAR_CORREO_ENVIADO = 'ERROR_ELIMINAR_CORREOS_ENVIADO';
export const ERROR_LISTAR_CORREOS_ENVIADOS = 'ERROR_LISTAR_CORREOS_ENVIADOS';
export const ERROR_CORREOS_ENVIADOS = 'ERROR_CORREOS_ENVIADOS';

export const SUCCESSFULL_INSERT_CORREO_ENVIADO = 'SUCCESSFULL_INSERT_CORREO_ENVIADO';
export const SUCCESSFULL_UPDATE_CORREO_ENVIADO = 'SUCCESSFULL_UPDATE_CORREO_ENVIADO';
export const SUCCESSFULL_DELETE_CORREO_ENVIADO = 'SUCCESSFULL_DELETE_CORREO_ENVIADO';