
/*
	Estados del reducer
*/
export const VER_CUENTA_CORREO = 'VER_CUENTA_CORREO';
export const INSERTAR_CUENTA_CORREO = 'INSERTAR_CUENTA_CORREO';
export const ELIMINAR_CUENTA_CORREO = 'ELIMINAR_CUENTA_CORREO';
export const LISTAR_CUENTAS_CORREOS = 'LISTAR_CUENTAS_CORREOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_CUENTA_CORREO = 'ERROR_INSERTAR_CUENTA_CORREO';
export const ERROR_ACTUALIZAR_CUENTA_CORREO = 'ERROR_ACTUALIZAR_CUENTA_CORREO';
export const ERROR_ELIMINAR_CUENTA_CORREO = 'ERROR_ELIMINAR_CUENTA_CORREO';
export const ERROR_LISTAR_CUENTAS_CORREOS = 'ERROR_LISTAR_CUENTAS_CORREOS';
export const ERROR_CUENTA_CORREO = 'ERROR_CUENTA_CORREO';

export const SUCCESSFULL_INSERT_CUENTA_CORREO = 'SUCCESSFULL_INSERT_CUENTA_CORREO';
export const SUCCESSFULL_UPDATE_CUENTA_CORREO = 'SUCCESSFULL_UPDATE_CUENTA_CORREO';
export const SUCCESSFULL_DELETE_CUENTA_CORREO = 'SUCCESSFULL_DELETE_CUENTA_CORREO';