
/*
	Estados del reducer
*/
export const VER_DETALLE_TAREA = 'VER_DETALLE_TAREA';
export const INSERTAR_DETALLE_TAREA = 'INSERTAR_DETALLE_TAREA';
export const ELIMINAR_DETALLE_TAREA = 'ELIMINAR_DETALLE_TAREA';
export const LISTAR_DETALLE_TAREAS = 'LISTAR_DETALLE_TAREAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_DETALLE_TAREA = 'ERROR_INSERTAR_DETALLE_TAREA';
export const ERROR_ACTUALIZAR_DETALLE_TAREA = 'ERROR_ACTUALIZAR_DETALLE_TAREA';
export const ERROR_ELIMINAR_DETALLE_TAREA = 'ERROR_ELIMINAR_DETALLE_TAREA';
export const ERROR_LISTAR_DETALLE_TAREA = 'ERROR_LISTAR_DETALLES_TAREAS';
export const ERROR_DETALLE_TAREA = 'ERROR_DETALLE_TAREA';

export const SUCCESSFULL_INSERT_DETALLE_TAREA = 'SUCCESSFULL_INSERT_DETALLE_TAREA';
export const SUCCESSFULL_UPDATE_DETALLE_TAREA = 'SUCCESSFULL_UPDATE_DETALLE_TAREA';
export const SUCCESSFULL_DELETE_DETALLE_TAREA = 'SUCCESSFULL_DELETE_DETALLE_TAREA';