
/*
	Estados del reducer
*/
export const VER_ESTUDIANTE_CURSO = 'VER_ESTUDIANTE_CURSO';
export const INSERTAR_ESTUDIANTE_CURSO = 'INSERTAR_ESTUDIANTE_CURSO';
export const ELIMINAR_ESTUDIANTE_CURSO = 'ELIMINAR_ESTUDIANTE_CURSO';
export const LISTAR_ESTUDIANTE_CURSOS = 'LISTAR_ESTUDIANTE_CURSOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_ESTUDIANTE_CURSO = 'ERROR_INSERTAR_ESTUDIANTE_CURSO';
export const ERROR_ACTUALIZAR_ESTUDIANTE_CURSO = 'ERROR_ACTUALIZAR_ESTUDIANTE_CURSO';
export const ERROR_ELIMINAR_ESTUDIANTE_CURSO = 'ERROR_ELIMINAR_ESTUDIANTE_CURSO';
export const ERROR_LISTAR_ESTUDIANTES_CURSOS = 'ERROR_LISTAR_ESTUDIANTES_CURSOS';
export const ERROR_ESTUDIANTE_CURSO = 'ERROR_ESTUDIANTE_CURSO';

export const SUCCESSFULL_INSERT_ESTUDIANTE_CURSO = 'SUCCESSFULL_INSERT_ESTUDIANTE_CURSO';
export const SUCCESSFULL_UPDATE_ESTUDIANTE_CURSO = 'SUCCESSFULL_UPDATE_ESTUDIANTE_CURSO';
export const SUCCESSFULL_DELETE_ESTUDIANTE_CURSO = 'SUCCESSFULL_DELETE_ESTUDIANTE_CURSO';