
/*
	Estados del reducer
*/
export const VER_GRUPO = 'VER_GRUPO';
export const INSERTAR_GRUPO = 'INSERTAR_GRUPO';
export const ELIMINAR_GRUPO = 'ELIMINAR_GRUPO';
export const LISTAR_GRUPOS = 'LISTAR_GRUPOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_GRUPO = 'ERROR_INSERTAR_GRUPO';
export const ERROR_ACTUALIZAR_GRUPO = 'ERROR_ACTUALIZAR_GRUPO';
export const ERROR_ELIMINAR_GRUPO = 'ERROR_ELIMINAR_GRUPO';
export const ERROR_LISTAR_GRUPOS = 'ERROR_LISTAR_GRUPOS';
export const ERROR_GRUPO = 'ERROR_GRUPO';

export const SUCCESSFULL_INSERT_GRUPO = 'SUCCESSFULL_INSERT_GRUPO';
export const SUCCESSFULL_UPDATE_GRUPO = 'SUCCESSFULL_UPDATE_GRUPO';
export const SUCCESSFULL_DELETE_GRUPO = 'SUCCESSFULL_DELETE_GRUPO';