
/*
	Estados del reducer
*/
export const VER_HORARIO_CURSO = 'VER_HORARIO_CURSO';
export const INSERTAR_HORARIO_CURSO = 'INSERTAR_HORARIO_CURSO';
export const ELIMINAR_HORARIO_CURSO = 'ELIMINAR_HORARIO_CURSO';
export const LISTAR_HORARIOS_CURSOS = 'LISTAR_HORARIOS_CURSOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_HORARIO_CURSO = 'ERROR_INSERTAR_HORARIO_CURSO';
export const ERROR_ACTUALIZAR_HORARIO_CURSO = 'ERROR_ACTUALIZAR_HORARIO_CURSO';
export const ERROR_ELIMINAR_HORARIO_CURSO = 'ERROR_ELIMINAR_HORARIO_CURSO';
export const ERROR_LISTAR_HORARIOS_CURSOS = 'ERROR_LISTAR_HORARIOS_CURSOS';
export const ERROR_HORARIO_CURSO = 'ERROR_HORARIO_CURSO';

export const SUCCESSFULL_INSERT_HORARIO_CURSO = 'SUCCESSFULL_INSERT_HORARIO_CURSO';
export const SUCCESSFULL_UPDATE_HORARIO_CURSO = 'SUCCESSFULL_UPDATE_HORARIO_CURSO';
export const SUCCESSFULL_DELETE_HORARIO_CURSO = 'SUCCESSFULL_DELETE_HORARIO_CURSO';