
/*
	Estados del reducer
*/
export const VER_INTEGRANTE_GRUPO = 'VER_INTEGRANTE_GRUPO';
export const INSERTAR_INTEGRANTE_GRUPO = 'INSERTAR_INTEGRANTE_GRUPO';
export const ELIMINAR_INTEGRANTE_GRUPO = 'ELIMINAR_INTEGRANTE_GRUPO';
export const LISTAR_INTEGRANTES_GRUPOS = 'LISTAR_INTEGRANTES_GRUPOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_INTEGRANTE_GRUPO = 'ERROR_INSERTAR_INTEGRANTE_GRUPO';
export const ERROR_ACTUALIZAR_INTEGRANTE_GRUPO = 'ERROR_ACTUALIZAR_INTEGRANTE_GRUPO';
export const ERROR_ELIMINAR_INTEGRANTE_GRUPO = 'ERROR_ELIMINAR_INTEGRANTE_GRUPO';
export const ERROR_LISTAR_INTEGRANTES_GRUPOS = 'ERROR_LISTAR_INTEGRANTES_GRUPOS';
export const ERROR_INTEGRANTE_GRUPO = 'ERROR_INTEGRANTE_GRUPO';

export const SUCCESSFULL_INSERT_INTEGRANTE_GRUPO = 'SUCCESSFULL_INSERT_INTEGRANTE_GRUPO';
export const SUCCESSFULL_UPDATE_INTEGRANTE_GRUPO = 'SUCCESSFULL_UPDATE_INTEGRANTE_GRUPO';
export const SUCCESSFULL_DELETE_INTEGRANTE_GRUPO = 'SUCCESSFULL_DELETE_INTEGRANTE_GRUPO';