
/*
	Estados del reducer
*/
export const VER_LIDER_SEMILLERO = 'VER_LIDER_SEMILLERO';
export const INSERTAR_LIDER_SEMILLERO = 'INSERTAR_LIDER_SEMILLERO';
export const ELIMINAR_LIDER_SEMILLERO = 'ELIMINAR_LIDER_SEMILLERO';
export const LISTAR_LIDERES_SEMILLEROS = 'LISTAR_LIDERES_SEMILLEROS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_LIDER_SEMILLERO = 'ERROR_INSERTAR_LIDER_SEMILLERO';
export const ERROR_ACTUALIZAR_LIDER_SEMILLERO = 'ERROR_ACTUALIZAR_LIDER_SEMILLERO';
export const ERROR_ELIMINAR_LIDER_SEMILLERO = 'ERROR_ELIMINAR_LIDER_SEMILLERO';
export const ERROR_LISTAR_LIDERES_SEMILLERO = 'ERROR_LISTAR_LIDERES_SEMILLERO';
export const ERROR_LIDER_SEMILLERO = 'ERROR_LIDER_SEMILLERO';

export const SUCCESSFULL_INSERT_LIDER_SEMILLERO = 'SUCCESSFULL_INSERT_LIDER_SEMILLERO';
export const SUCCESSFULL_UPDATE_LIDER_SEMILLERO = 'SUCCESSFULL_UPDATE_LIDER_SEMILLERO';
export const SUCCESSFULL_DELETE_LIDER_SEMILLERO = 'SUCCESSFULL_DELETE_LIDER_SEMILLERO';