
/*
	Estados del reducer
*/
export const VER_MENU_USUARIO = 'VER_MENU_USUARIO';
export const INSERTAR_MENU_USUARIO = 'INSERTAR_MENU_USUARIO';
export const ELIMINAR_MENU_USUARIO = 'ELIMINAR_MENU_USUARIO';
export const LISTAR_MENUS_USUARIOS = 'LISTAR_MENUS_USUARIOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_MENU_USUARIO = 'ERROR_INSERTAR_MENU_USUARIO';
export const ERROR_ACTUALIZAR_MENU_USUARIO = 'ERROR_ACTUALIZAR_MENU_USUARIO';
export const ERROR_ELIMINAR_MENU_USUARIO = 'ERROR_ELIMINAR_MENU_USUARIO';
export const ERROR_LISTAR_MENUS_USUARIOS = 'ERROR_LISTAR_MENUS_USUARIOS';
export const ERROR_MENU_USUARIO = 'ERROR_MENU_USUARIO';

export const SUCCESSFULL_INSERT_MENU_USUARIO = 'SUCCESSFULL_INSERT_MENU_USUARIO';
export const SUCCESSFULL_UPDATE_MENU_USUARIO = 'SUCCESSFULL_UPDATE_MENU_USUARIO';
export const SUCCESSFULL_DELETE_MENU_USUARIO = 'SUCCESSFULL_DELETE_MENU_USUARIO';