
/*
	Estados del reducer
*/
export const VER_NIVEL = 'VER_NIVEL';
export const INSERTAR_NIVEL = 'INSERTAR_NIVEL';
export const ELIMINAR_NIVEL = 'ELIMINAR_NIVEL';
export const LISTAR_NIVELES = 'LISTAR_NIVELES';



/*
	Estados de API
*/
export const ERROR_INSERTAR_NIVEL = 'ERROR_INSERTAR_NIVEL';
export const ERROR_ACTUALIZAR_NIVEL = 'ERROR_ACTUALIZAR_NIVEL';
export const ERROR_ELIMINAR_NIVEL = 'ERROR_ELIMINAR_NIVEL';
export const ERROR_LISTAR_NIVELES = 'ERROR_LISTAR_NIVELES';
export const ERROR_NIVEL = 'ERROR_NIVEL';

export const SUCCESSFULL_INSERT_NIVEL = 'SUCCESSFULL_INSERT_NIVEL';
export const SUCCESSFULL_UPDATE_NIVEL = 'SUCCESSFULL_UPDATE_NIVEL';
export const SUCCESSFULL_DELETE_NIVEL = 'SUCCESSFULL_DELETE_NIVEL';