
/*
	Estados del reducer
*/
export const VER_NOTICIA = 'VER_NOTICIA';
export const INSERTAR_NOTICIA = 'INSERTAR_NOTICIA';
export const ELIMINAR_NOTICIA = 'ELIMINAR_NOTICIA';
export const LISTAR_NOTICIAS = 'LISTAR_NOTICIAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_NOTICIA = 'ERROR_INSERTAR_NOTICIA';
export const ERROR_ACTUALIZAR_NOTICIA = 'ERROR_ACTUALIZAR_NOTICIA';
export const ERROR_ELIMINAR_NOTICIA = 'ERROR_ELIMINAR_NOTICIA';
export const ERROR_LISTAR_NOTICIAS = 'ERROR_LISTAR_NOTICIAS';
export const ERROR_NOTICIA = 'ERROR_NOTICIA';

export const SUCCESSFULL_INSERT_NOTICIA = 'SUCCESSFULL_INSERT_NOTICIA';
export const SUCCESSFULL_UPDATE_NOTICIA = 'SUCCESSFULL_UPDATE_NOTICIA';
export const SUCCESSFULL_DELETE_NOTICIA = 'SUCCESSFULL_DELETE_NOTICIA';