
/*
	Estados del reducer
*/
export const VER_NOTIFICACION = 'VER_NOTIFICACION';
export const INSERTAR_NOTIFICACION = 'INSERTAR_NOTIFICACION';
export const ELIMINAR_NOTIFICACION = 'ELIMINAR_NOTIFICACION';
export const LISTAR_NOTIFICACIONES = 'LISTAR_NOTIFICACIONES';



/*
	Estados de API
*/
export const ERROR_INSERTAR_NOTIFICACION = 'ERROR_INSERTAR_NOTIFICACION';
export const ERROR_ACTUALIZAR_NOTIFICACION = 'ERROR_ACTUALIZAR_NOTIFICACION';
export const ERROR_ELIMINAR_NOTIFICACION = 'ERROR_ELIMINAR_NOTIFICACION';
export const ERROR_LISTAR_NOTIFICACIONES = 'ERROR_LISTAR_NOTIFICACIONES';
export const ERROR_NOTIFICACION = 'ERROR_NOTIFICACION';

export const SUCCESSFULL_INSERT_NOTIFICACION = 'SUCCESSFULL_INSERT_NOTIFICACION';
export const SUCCESSFULL_UPDATE_NOTIFICACION = 'SUCCESSFULL_UPDATE_NOTIFICACION';
export const SUCCESSFULL_DELETE_NOTIFICACION = 'SUCCESSFULL_DELETE_NOTIFICACION';