/**
 * Estados del reducer
 */

export const VER_PERMISO = "VER_PERMISO";
export const INSERTAR_PERMISO = "INSERTAR_PERMISO";
export const ELIMINAR_PERMISO = "ELIMINAR_PERMISO";
export const LISTAR_PERMISOS = "LISTAR_PERMISOS";

/**
 * Estados del api
 */
export const ERROR_INSERTAR_PERMISO = "ERROR_INSERTAR_PERMISO";
export const ERROR_ACTUALIZAR_PERMISO = "ERROR_ACTUALIZAR_PERMISO";
export const ERROR_ELIMINAR_PERMISO = "ERROR_ELIMINAR_PERMISO";
export const ERROR_LISTAR_PERMISO = "ERROR_LISTAR_PERMISO";

export const SUCCESSFULL_INSERT_PERMISO = "SUCCESSFULL_INSERT_PERMISO";
export const SUCCESSFULL_UPDATE_PERMISO = "SUCCESSFULL_UPDATE_PERMISO";
export const SUCCESSFULL_DELETE_PERMISO = "SUCCESSFULL_DELETE_PERMISO";