
/*
	Estados del reducer
*/
export const VER_PROGRAMA_SEMILLERO = 'VER_PROGRAMA_SEMILLERO';
export const INSERTAR_PROGRAMA_SEMILLERO = 'INSERTAR_PROGRAMA_SEMILLERO';
export const ELIMINAR_PROGRAMA_SEMILLERO = 'ELIMINAR_PROGRAMA_SEMILLERO';
export const LISTAR_PROGRAMAS_SEMILLEROS = 'LISTAR_PROGRAMAS_SEMILLEROS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_PROGRAMA_SEMILLERO = 'ERROR_INSERTAR_PROGRAMA_SEMILLERO';
export const ERROR_ACTUALIZAR_PROGRAMA_SEMILLERO = 'ERROR_ACTUALIZAR_PROGRAMA_SEMILLERO';
export const ERROR_ELIMINAR_PROGRAMA_SEMILLERO = 'ERROR_ELIMINAR_PROGRAMA_SEMILLERO';
export const ERROR_LISTAR_PROGRAMAS_SEMILLEROS = 'ERROR_LISTAR_PROGRAMAS_SEMILLEROS';
export const ERROR_PROGRAMA_SEMILLERO = 'ERROR_PROGRAMA_SEMILLERO';

export const SUCCESSFULL_INSERT_PROGRAMA_SEMILLERO = 'SUCCESSFULL_INSERT_PROGRAMA_SEMILLERO';
export const SUCCESSFULL_UPDATE_PROGRAMA_SEMILLERO = 'SUCCESSFULL_UPDATE_PROGRAMA_SEMILLERO';
export const SUCCESSFULL_DELETE_PROGRAMA_SEMILLERO = 'SUCCESSFULL_DELETE_PROGRAMA_SEMILLERO';