
/*
	Estados del reducer
*/
export const VER_PROGRAMA = 'VER_PROGRAMA';
export const INSERTAR_PROGRAMA = 'INSERTAR_PROGRAMA';
export const ELIMINAR_PROGRAMA = 'ELIMINAR_PROGRAMA';
export const LISTAR_PROGRAMAS = 'LISTAR_PROGRAMAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_PROGRAMA = 'ERROR_INSERTAR_PROGRAMA';
export const ERROR_ACTUALIZAR_PROGRAMA = 'ERROR_ACTUALIZAR_PROGRAMA';
export const ERROR_ELIMINAR_PROGRAMA = 'ERROR_ELIMINAR_PROGRAMA';
export const ERROR_LISTAR_PROGRAMAS = 'ERROR_LISTAR_PROGRAMAS';
export const ERROR_PROGRAMA = 'ERROR_PROGRAMA';

export const SUCCESSFULL_INSERT_PROGRAMA = 'SUCCESSFULL_INSERT_PROGRAMA';
export const SUCCESSFULL_UPDATE_PROGRAMA = 'SUCCESSFULL_UPDATE_PROGRAMA';
export const SUCCESSFULL_DELETE_PROGRAMA = 'SUCCESSFULL_DELETE_PROGRAMA';