
/*
	Estados del reducer
*/
export const VER_PROYECTO = 'VER_PROYECTO';
export const INSERTAR_PROYECTO = 'INSERTAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';
export const LISTAR_PROYECTOS = 'LISTAR_PROYECTOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_PROYECTO = 'ERROR_INSERTAR_PROYECTO';
export const ERROR_ACTUALIZAR_PROYECTO = 'ERROR_ACTUALIZAR_PROYECTO';
export const ERROR_ELIMINAR_PROYECTO = 'ERROR_ELIMINAR_PROYECTO';
export const ERROR_LISTAR_PROYECTOS = 'ERROR_LISTAR_PROYECTOS';
export const ERROR_PROYECTO = 'ERROR_PROYECTO';

export const SUCCESSFULL_INSERT_PROYECTO = 'SUCCESSFULL_INSERT_PROYECTO';
export const SUCCESSFULL_UPDATE_PROYECTO = 'SUCCESSFULL_UPDATE_PROYECTO';
export const SUCCESSFULL_DELETE_PROYECTO = 'SUCCESSFULL_DELETE_PROYECTO';