
/*
	Estados del reducer
*/
export const VER_ROL_SEMILLERO = 'VER_ROL_SEMILLERO';
export const INSERTAR_ROL_SEMILLERO = 'INSERTAR_ROL_SEMILLERO';
export const ELIMINAR_ROL_SEMILLERO = 'ELIMINAR_ROL_SEMILLERO';
export const LISTAR_ROLES_SEMILLEROS = 'LISTAR_ROLES_SEMILLEROS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_ROL_SEMILLERO = 'ERROR_INSERTAR_ROL_SEMILLERO';
export const ERROR_ACTUALIZAR_ROL_SEMILLERO = 'ERROR_ACTUALIZAR_ROL_SEMILLERO';
export const ERROR_ELIMINAR_ROL_SEMILLERO = 'ERROR_ELIMINAR_ROL_SEMILLERO';
export const ERROR_LISTAR_ROLES_SEMILLEROS = 'ERROR_LISTAR_ROLES_SEMILLEROS';
export const ERROR_ROL_SEMILLERO = 'ERROR_ROL_SEMILLERO';

export const SUCCESSFULL_INSERT_ROL_SEMILLERO = 'SUCCESSFULL_INSERT_ROL_SEMILLERO';
export const SUCCESSFULL_UPDATE_ROL_SEMILLERO = 'SUCCESSFULL_UPDATE_ROL_SEMILLERO';
export const SUCCESSFULL_DELETE_ROL_SEMILLERO = 'SUCCESSFULL_DELETE_ROL_SEMILLERO';