/*
  Estados del reducer
 */
export const VER_SEMILLERO = 'VER_SEMILLERO';
export const INSERTAR_SEMILLERO = 'INSERTAR_SEMILLERO';
export const ELIMINAR_SEMILLERO = 'ELIMINAR_SEMILLERO';
export const LISTAR_SEMILLEROS = 'LISTAR_SEMILLEROS';

/*
Estados de api
 */
export const ERROR_INSERTAR_SEMILLERO = 'ERROR_INSERTAR_SEMILLERO';
export const ERROR_ACTUALIZAR_SEMILLERO = 'ERROR_ACTUALIZAR_SEMILLERO';
export const ERROR_ELIMINAR_SEMILLERO = 'ERROR_ELIMINAR_SEMILLERO';
export const ERROR_LISTAR_SEMILLERO = 'ERROR_LISTAR_SEMILLERO';

export const SUCCESSFULL_INSERT_SEMILLERO = 'SUCCESSFULL_INSERT_SEMILLERO';
export const SUCCESSFULL_UPDATE_SEMILLERO = 'SUCCESSFULL_UPDATE_SEMILLERO';
export const SUCCESSFULL_DELETE_SEMILLERO = 'SUCCESSFULL_DELETE_SEMILLERO';
