
/*
	Estados del reducer
*/
export const VER_SUBPERMISO = 'VER_SUBPERMISO';
export const INSERTAR_SUBPERMISO = 'INSERTAR_SUBPERMISO';
export const ELIMINAR_SUBPERMISO = 'ELIMINAR_SUBPERMISO';
export const LISTAR_SUBPERMISOS = 'LISTAR_SUBPERMISOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_SUBPERMISO = 'ERROR_INSERTAR_SUBPERMISO';
export const ERROR_ACTUALIZAR_SUBPERMISO = 'ERROR_ACTUALIZAR_SUBPERMISO';
export const ERROR_ELIMINAR_SUBPERMISO = 'ERROR_ELIMINAR_SUBPERMISO';
export const ERROR_LISTAR_SUBPERMISOS = 'ERROR_LISTAR_SUBPERMISOS';
export const ERROR_SUBPERMISO = 'ERROR_SUBPERMISO';

export const SUCCESSFULL_INSERT_SUBPERMISO = 'SUCCESSFULL_INSERT_SUBPERMISO';
export const SUCCESSFULL_UPDATE_SUBPERMISO = 'SUCCESSFULL_UPDATE_SUBPERMISO';
export const SUCCESSFULL_DELETE_SUBPERMISO = 'SUCCESSFULL_DELETE_SUBPERMISO';