
/*
	Estados del reducer
*/
export const VER_TAREA = 'VER_TAREA';
export const INSERTAR_TAREA = 'INSERTAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const LISTAR_TAREAS = 'LISTAR_TAREAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_TAREA = 'ERROR_INSERTAR_TAREA';
export const ERROR_ACTUALIZAR_TAREA = 'ERROR_ACTUALIZAR_TAREA';
export const ERROR_ELIMINAR_TAREA = 'ERROR_ELIMINAR_TAREA';
export const ERROR_LISTAR_TAREAS = 'ERROR_LISTAR_TAREAS';
export const ERROR_TAREA = 'ERROR_TAREA';

export const SUCCESSFULL_INSERT_TAREA = 'SUCCESSFULL_INSERT_TAREA';
export const SUCCESSFULL_UPDATE_TAREA = 'SUCCESSFULL_UPDATE_TAREA';
export const SUCCESSFULL_DELETE_TAREA = 'SUCCESSFULL_DELETE_TAREA';