
/*
	Estados del reducer
*/
export const VER_TIPO_NOTIFICACION = 'VER_TIPO_NOTIFICACION';
export const INSERTAR_TIPO_NOTIFICACION = 'INSERTAR_TIPO_NOTIFICACION';
export const ELIMINAR_TIPO_NOTIFICACION = 'ELIMINAR_TIPO_NOTIFICACION';
export const LISTAR_TIPOS_NOTIFICACIONES = 'LISTAR_TIPOS_NOTIFICACIONES';



/*
	Estados de API
*/
export const ERROR_INSERTAR_TIPO_NOTIFICACION = 'ERROR_INSERTAR_TIPO_NOTIFICACION';
export const ERROR_ACTUALIZAR_TIPO_NOTIFICACION = 'ERROR_ACTUALIZAR_TIPO_NOTIFICACION';
export const ERROR_ELIMINAR_TIPO_NOTIFICACION = 'ERROR_ELIMINAR_TIPO_NOTIFICACION';
export const ERROR_LISTAR_TIPOS_NOTIFICACIONES = 'ERROR_LISTAR_TIPOS_NOTIFICACIONES';
export const ERROR_TIPO_NOTIFICACION = 'ERROR_TIPO_NOTIFICACION';

export const SUCCESSFULL_INSERT_TIPO_NOTIFICACION = 'SUCCESSFULL_INSERT_TIPO_NOTIFICACION';
export const SUCCESSFULL_UPDATE_TIPO_NOTIFICACION = 'SUCCESSFULL_UPDATE_TIPO_NOTIFICACION';
export const SUCCESSFULL_DELETE_TIPO_NOTIFICACION = 'SUCCESSFULL_DELETE_TIPO_NOTIFICACION';