
/*
	Estados del reducer
*/
export const VER_TIPO_CURSO = 'VER_TIPO_CURSO';
export const INSERTAR_TIPO_CURSO = 'INSERTAR_TIPO_CURSO';
export const ELIMINAR_TIPO_CURSO = 'ELIMINAR_TIPO_CURSO';
export const LISTAR_TIPOS_CURSOS = 'LISTAR_TIPOS_CURSOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_TIPO_CURSO = 'ERROR_INSERTAR_TIPO_CURSO';
export const ERROR_ACTUALIZAR_TIPO_CURSO = 'ERROR_ACTUALIZAR_TIPO_CURSO';
export const ERROR_ELIMINAR_TIPO_CURSO = 'ERROR_ELIMINAR_TIPO_CURSO';
export const ERROR_LISTAR_TIPOS_CURSOS = 'ERROR_LISTAR_TIPOS_CURSOS';
export const ERROR_TIPO_CURSO = 'ERROR_TIPO_CURSO';

export const SUCCESSFULL_INSERT_TIPO_CURSO = 'SUCCESSFULL_INSERT_TIPO_CURSO';
export const SUCCESSFULL_UPDATE_TIPO_CURSO = 'SUCCESSFULL_UPDATE_TIPO_CURSO';
export const SUCCESSFULL_DELETE_TIPO_CURSO = 'SUCCESSFULL_DELETE_TIPO_CURSO';