
/*
	Estados del reducer
*/
export const VER_TIPO_NOTICIA = 'VER_TIPO_NOTICIA';
export const INSERTAR_TIPO_NOTICIA = 'INSERTAR_TIPO_NOTICIA';
export const ELIMINAR_TIPO_NOTICIA = 'ELIMINAR_TIPO_NOTICIA';
export const LISTAR_TIPOS_NOTICIAS = 'LISTAR_TIPOS_NOTICIAS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_TIPO_NOTICIA = 'ERROR_INSERTAR_TIPO_NOTICIA';
export const ERROR_ACTUALIZAR_TIPO_NOTICIA = 'ERROR_ACTUALIZAR_TIPO_NOTICIA';
export const ERROR_ELIMINAR_TIPO_NOTICIA = 'ERROR_ELIMINAR_TIPO_NOTICIA';
export const ERROR_LISTAR_TIPOS_NOTICIAS = 'ERROR_LISTAR_TIPOS_NOTICIAS';
export const ERROR_TIPO_NOTICIA = 'ERROR_TIPO_NOTICIA';

export const SUCCESSFULL_INSERT_TIPO_NOTICIA = 'SUCCESSFULL_INSERT_TIPO_NOTICIA';
export const SUCCESSFULL_UPDATE_TIPO_NOTICIA = 'SUCCESSFULL_UPDATE_TIPO_NOTICIA';
export const SUCCESSFULL_DELETE_TIPO_NOTICIA = 'SUCCESSFULL_DELETE_TIPO_NOTICIA';