
/*
	Estados del reducer
*/
export const VER_USUARIO = 'VER_USUARIO';
export const INSERTAR_USUARIO = 'INSERTAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const LISTAR_USUARIOS = 'LISTAR_USUARIOS';



/*
	Estados de API
*/
export const ERROR_INSERTAR_USUARIO = 'ERROR_INSERTAR_USUARIO';
export const ERROR_ACTUALIZAR_USUARIO = 'ERROR_ACTUALIZAR_USUARIO';
export const ERROR_ELIMINAR_USUARIO = 'ERROR_ELIMINAR_USUARIO';
export const ERROR_LISTAR_USUARIOS = 'ERROR_LISTAR_USUARIOS';
export const ERROR_USUARIO = 'ERROR_USUARIO';

export const SUCCESSFULL_INSERT_USUARIO = 'SUCCESSFULL_INSERT_USUARIO';
export const SUCCESSFULL_UPDATE_USUARIO = 'SUCCESSFULL_UPDATE_USUARIO';
export const SUCCESSFULL_DELETE_USUARIO = 'SUCCESSFULL_DELETE_USUARIO';